name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Build, check, lint, test (${{ matrix.os }}, Node ${{ matrix.node }})

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['14.x']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm, install dependencies, and build APIs
        uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: |
            args: [--frozen-lockfile]

      - name: Check
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
